name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-n3ds:
    name: Build (N3DS)
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install 3DS Libraries
        run: |
          sudo dkp-pacman -S --needed --noconfirm \
              3ds-pkg-config 3dslink 3dstools tex3ds libctru citro3d citro2d

      - name: Download makerom
        uses: robinraju/release-downloader@v1
        with:
          repository: "3DSGuy/Project_CTR"
          tag: "makerom-v0.19.0"
          fileName: "makerom-v0.19.0-ubuntu_x86_64.zip"

      - name: Download bannertool
        uses: robinraju/release-downloader@v1
        with:
          repository: "Epicpkmn11/bannertool"
          tag: "v1.2.2"
          fileName: "bannertool.zip"

      - name: Setup Tools
        run: |
          # Setup makerom
          unzip makerom-v0.19.0-ubuntu_x86_64.zip
          chmod +x makerom
          sudo mv makerom /opt/devkitpro/tools/bin/

          # Setup bannertool
          unzip bannertool.zip
          sudo mv linux-x86_64/bannertool /opt/devkitpro/tools/bin/bannertool
          sudo chmod +x /opt/devkitpro/tools/bin/bannertool

      - name: Build
        run: |
          make -j$(nproc)
          make cia

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: butterscotch-n3ds
          path: |
            *.3dsx
            *.cia
